vim.g.mapleader = ' ' -- Set <space> as the leader key
vim.g.maplocalleader = ' '

require "user.plugins"
require "user.options"
require "user.keymaps"
require "user.commands"
require "user.lsp"
require "user.treesitter"
require "user.cmp"
require "user.telescope"
require "user.gitsigns"
require "user.nvim-tree"
require "user.comment"
require "user.autopairs"
require "user.diffview"
require "user.symbols-outline"
require "user.ufo"
require "user.toggleterm"
require "user.bufferline"
require "user.rush_hdl"
